# Generated by Django 3.1.2 on 2020-11-11 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('rep', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.exercise')),
                ('sets', models.ManyToManyField(to='workout.Set')),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workout.workout')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
